server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false
        http-only: true
        path: /
        max-age: 1800

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5332/tracklytics}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Add session configuration
  session:
    store-type: memory
    timeout: 1800s

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/spotify
            scope:
              - user-read-private
              - user-read-email
              - user-read-recently-played
              - user-top-read
              - user-read-playback-state
            authorization-grant-type: authorization_code
            client-name: Spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

# JWT Configuration (optional section if you want to customize)
jwt:
  secret: ${JWT_SECRET:tracklytics-jwt-secret-key-must-be-at-least-32-characters-long-for-security}
  expiration: ${JWT_EXPIRATION:86400}